name: run python program with dependencies
on:
    push:
        branches:
            -main

jobs:
    extract_data:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: show python version
              run: python --version
